### PR TITLE
Added keyboard reading to move on screen

### PR DESCRIPTION
**Pull request by sikorka**
Hey @miron-kuzniar 
Could you check the code and try run `ConsoleMoves`? It's a class with `main()` method which needs to be run from console and demonstrates reading move related keys from keyboard. 
Thank you 🌞

### CODE REVIEW

**Comment by miron-kuzniar** [comment]
@sikorka 

stupid question - how can I run this from console? :rabbit:

**Comment by sikorka** [comment]
Open a console and do what `README.md` says. Always check `README.md` 👍

**Comment by sikorka** [comment]
[As a user I can move on the map](https://trello.com/c/2CePO7VG/6-as-a-user-i-can-move-on-the-map)

**Comment by sikorka** [comment]
I added moves on `Board` for `Janush` using the method from `ConsoleMoves`. @miron-kuzniar could you review? Thank you 👍

**Pull request merged**
