### PR TITLE
Created Unit Test no 3

### PR DESCRIPTION
**Pull request by miron-kuzniar**
This test verifies amount of Grid rows displayed.

### CODE REVIEW

**Comment by miron-kuzniar** [comment]
@kbrenzak Could you review the code? :)

**Comment by miron-kuzniar** [comment]
[Implement unit test for Grid](https://trello.com/c/Zd7Cap9h/48-implement-unit-test-for-grid)

**Comment by kbrenzak** [comment]
@miron-kuzniar looks great and working fine :+1:  I think I also should use your method :smiley:

**Comment by kbrenzak** [comment]
@miron-kuzniar  I am just not sure how the pom file should look like - there is a conflict

**Comment by miron-kuzniar** [comment]
@kbrenzak Yes - there is a conflict in pom - there was junit implemented 3 times, so I deleted unnecessary dependencies. 
Thank you for review - I will merge this with master :)

Feel free to use my method :P

**Comment by miron-kuzniar** [comment]
Conflicts resolved.
@kbrenzak please merge pull request and delete my branch.

**Pull request merged**
