### PR TITLE
Small changes

### PR DESCRIPTION
**Pull request by miron-kuzniar**
"Lives" changed to "Lifes", moves printing aligned to one line.

### CODE REVIEW

**Comment by miron-kuzniar** [comment]
@kbrenzak 

Please review:)

**Comment by miron-kuzniar** [comment]
[Small changes](https://trello.com/c/RdWc2gkq/66-small-changes)

**Comment by kbrenzak** [comment]
Hi @miron-kuzniar Your changes look good and I wanted to merged them into master, but there is some conflict. Could you take a look and first merge master with your branch? :smile:

**Comment by miron-kuzniar** [comment]
Hi @kbrenzak 

I pushed tests which we've created at weekly meeting with Ania. Please just take a look and I will resolve conflicts:)

**Pull request closed without merging**
