### PR TITLE
Put them on grid

### PR DESCRIPTION
**Pull request by sikorka**
Hello @miron-kuzniar Could you have a look and review? 🌤 

How it works: 
Multiple runs of `MainApp` will produce different games and so, different results - sometimes Janush wins, sometimes not. Moving on grid is currently static - always 3 rows up and 2 left. 

Changes relate to what we spoke of during recent training(s): 
- implemented displaying `Janush` and `Beer` on grid - we spoke how to do it last time 
- implemented `Beer` and `Janush` to derive from `Positionable` - we also spoke this is needed and how to do it (I could not leave this for later with all other changes being implemented) 
- implemented example test for `Positionable` 
- improved `README.md`, `.gitignore` and javadoc comments 

This branch was based on your branch `miron_counter`. I have left the `TimerTask` with comments what is an obstacle in using it - you can uncomment this code in `MainApp` to try. Later on you can remove it when implementing something simpler as we spoke (like a loop or similar).

### CODE REVIEW

**Comment by sikorka** [comment]
[Beer and Janush need to inherit from abstract Positionable class](https://trello.com/c/MHhPYV0c/51-beer-and-janush-need-to-inherit-from-abstract-positionable-class)

**Comment by sikorka** [comment]
[As a Developer I need Beer class implemented in model](https://trello.com/c/IjHLScY1/30-as-a-developer-i-need-beer-class-implemented-in-model)

**Comment by sikorka** [comment]
[As a developer I want to have Janush initial / set position shown on the grid](https://trello.com/c/2EYXhjCF/47-as-a-developer-i-want-to-have-janush-initial-%2F-set-position-shown-on-the-grid)

**Comment by miron-kuzniar** [comment]
Everything is ok - checked with team on weekly meeting.
Thank you @sikorka

**Pull request merged**
